// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ST_Assignment_1.Data;

#nullable disable

namespace ST_Assignment_1.Migrations
{
    [DbContext(typeof(WorkoutJournalDbContext))]
    [Migration("20250927183606_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ST_Assignment_1.Data.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentTemplateId = 1
                        });
                });

            modelBuilder.Entity("ST_Assignment_1.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultReps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultRestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultSets")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            DefaultReps = "8-15",
                            DefaultRestSeconds = 75,
                            DefaultSets = 3,
                            Description = "Standard push-up. Keep body aligned.",
                            Difficulty = 0,
                            Name = "Push-up"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            DefaultReps = "8-20",
                            DefaultRestSeconds = 60,
                            DefaultSets = 3,
                            Description = "Incline push-up.",
                            Difficulty = 0,
                            Name = "Incline Push-up"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            DefaultReps = "6-12",
                            DefaultRestSeconds = 90,
                            DefaultSets = 3,
                            Description = "Diamond push-up.",
                            Difficulty = 1,
                            Name = "Diamond Push-up"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            DefaultReps = "6-12",
                            DefaultRestSeconds = 105,
                            DefaultSets = 3,
                            Description = "Pike push-up.",
                            Difficulty = 1,
                            Name = "Pike Push-up"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            DefaultReps = "3-10",
                            DefaultRestSeconds = 135,
                            DefaultSets = 4,
                            Description = "Pull-up.",
                            Difficulty = 1,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            DefaultReps = "3-10",
                            DefaultRestSeconds = 135,
                            DefaultSets = 4,
                            Description = "Chin-up.",
                            Difficulty = 1,
                            Name = "Chin-up"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            DefaultReps = "8-15",
                            DefaultRestSeconds = 75,
                            DefaultSets = 3,
                            Description = "Bodyweight row.",
                            Difficulty = 0,
                            Name = "Bodyweight Row (Australian Pull-up)"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            DefaultReps = "6-15",
                            DefaultRestSeconds = 105,
                            DefaultSets = 3,
                            Description = "Parallel bar dips.",
                            Difficulty = 1,
                            Name = "Dips (parallel bar)"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            DefaultReps = "12-20",
                            DefaultRestSeconds = 60,
                            DefaultSets = 3,
                            Description = "Bodyweight squat.",
                            Difficulty = 0,
                            Name = "Squat (bodyweight)"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            DefaultReps = "8-15",
                            DefaultRestSeconds = 75,
                            DefaultSets = 3,
                            Description = "Jump squat.",
                            Difficulty = 1,
                            Name = "Jump Squat"
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            DefaultReps = "3-8",
                            DefaultRestSeconds = 135,
                            DefaultSets = 4,
                            Description = "Assisted pistol squat.",
                            Difficulty = 2,
                            Name = "Pistol Squat (assisted)"
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            DefaultReps = "8-15",
                            DefaultRestSeconds = 75,
                            DefaultSets = 3,
                            Description = "Lunges.",
                            Difficulty = 0,
                            Name = "Lunges (walking/static)"
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            DefaultReps = "30-90s",
                            DefaultRestSeconds = 60,
                            DefaultSets = 3,
                            Description = "Plank.",
                            Difficulty = 0,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            DefaultReps = "8-15",
                            DefaultRestSeconds = 75,
                            DefaultSets = 3,
                            Description = "Hanging leg raise.",
                            Difficulty = 1,
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 15,
                            Category = 4,
                            DefaultReps = "30s",
                            DefaultRestSeconds = 45,
                            DefaultSets = 3,
                            Description = "Mountain climbers.",
                            Difficulty = 0,
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = 16,
                            Category = 4,
                            DefaultReps = "6-15",
                            DefaultRestSeconds = 90,
                            DefaultSets = 3,
                            Description = "Burpee.",
                            Difficulty = 1,
                            Name = "Burpee"
                        });
                });

            modelBuilder.Entity("ST_Assignment_1.Models.ExerciseTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("TargetReps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetRestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            Notes = "Push-ups: 10 reps, 3 sets, 5 min rest",
                            Order = 1,
                            TargetReps = "10",
                            TargetRestSeconds = 300,
                            TargetSets = 3,
                            TemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            Notes = "Squats: 15 reps, 3 sets, 5 min rest",
                            Order = 2,
                            TargetReps = "15",
                            TargetRestSeconds = 300,
                            TargetSets = 3,
                            TemplateId = 1
                        });
                });

            modelBuilder.Entity("ST_Assignment_1.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A simple full body routine.",
                            Frequency = 0,
                            Name = "Full Body Example"
                        });
                });

            modelBuilder.Entity("ST_Assignment_1.Models.ExerciseTemplateItem", b =>
                {
                    b.HasOne("ST_Assignment_1.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ST_Assignment_1.Models.Template", null)
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("ST_Assignment_1.Models.Template", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
